import { Car } from '@/types';

const WHATSAPP = process.env.NEXT_PUBLIC_WHATSAPP_NUMBER || '22997000000';

export const mockCars: Car[] = [
  {
    id: 'car-1',
    slug: 'toyota-land-cruiser-2022',
    title: 'Toyota Land Cruiser 2022',
    brand: 'Toyota',
    model: 'Land Cruiser',
    year: 2022,
    category: 'SUV',
    city: 'Cotonou',
    pricePerDay: 75000,
    depositAmount: 150000,
    chauffeurAvailable: true,
    chauffeurPricePerDay: 20000,
    transmission: 'automatic',
    fuelType: 'diesel',
    seats: 7,
    description:
      'Le Toyota Land Cruiser est le SUV par excellence, idéal pour les routes de Cotonou et ses environs. Confortable, robuste et spacieux, il s\'adapte à tous vos déplacements professionnels ou familiaux.',
    mainImageUrl: 'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?w=800',
    images: [
      'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?w=800',
      'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=800',
      'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=800',
    ],
    pickupZone: 'Cotonou — livraison possible à l\'aéroport, hôtels, adresse personnelle',
    includedZones: ['Cotonou', 'Abomey-Calavi', 'Porto-Novo', 'Grand-Popo'],
    features: ['Climatisation', 'GPS', 'Siège enfant disponible', 'Toit ouvrant', 'Caméra de recul', '4x4 tout-terrain'],
    rentalPolicy: 'Permis de conduire valide exigé. Le véhicule est remis avec un plein — à restituer avec un plein. Kilométrage illimité dans les zones incluses.',
    cancellationPolicy: 'Annulation gratuite jusqu\'à 48h avant la prise en charge. En dessous de 48h, la caution est conservée.',
    whatsappPhone: WHATSAPP,
    status: 'active',
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'car-2',
    slug: 'mercedes-classe-e-2023',
    title: 'Mercedes Classe E 2023',
    brand: 'Mercedes',
    model: 'Classe E',
    year: 2023,
    category: 'Berline',
    city: 'Cotonou',
    pricePerDay: 90000,
    depositAmount: 200000,
    chauffeurAvailable: true,
    chauffeurPricePerDay: 25000,
    transmission: 'automatic',
    fuelType: 'petrol',
    seats: 5,
    description:
      'La Mercedes Classe E incarne le luxe et l\'élégance allemande. Parfaite pour les voyages d\'affaires et les occasions spéciales à Cotonou.',
    mainImageUrl: 'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=800',
    images: [
      'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=800',
      'https://images.unsplash.com/photo-1555215695-3004980ad54e?w=800',
      'https://images.unsplash.com/photo-1494976388531-d1058494cdd8?w=800',
    ],
    pickupZone: 'Cotonou — livraison hôtels premium et aéroport',
    includedZones: ['Cotonou', 'Porto-Novo'],
    features: ['Climatisation bi-zone', 'Cuir', 'Massage siège conducteur', 'Affichage tête haute', 'Wifi embarqué', 'Chargeur sans fil'],
    rentalPolicy: 'Permis valide + pièce d\'identité requis. Carburant non inclus. Livraison hôtel en option (+5 000 XOF).',
    cancellationPolicy: 'Annulation gratuite jusqu\'à 48h avant. Remboursement intégral de la caution si véhicule restitué en bon état.',
    whatsappPhone: WHATSAPP,
    status: 'active',
    created_at: '2024-01-02T00:00:00Z',
  },
  {
    id: 'car-3',
    slug: 'bmw-serie-5-2022',
    title: 'BMW Série 5 2022',
    brand: 'BMW',
    model: 'Série 5',
    year: 2022,
    category: 'Berline',
    city: 'Cotonou',
    pricePerDay: 85000,
    depositAmount: 180000,
    chauffeurAvailable: true,
    chauffeurPricePerDay: 22000,
    transmission: 'automatic',
    fuelType: 'petrol',
    seats: 5,
    description:
      'La BMW Série 5 allie performance sportive et confort premium. Un choix idéal pour les professionnels exigeants en déplacement à Cotonou.',
    mainImageUrl: 'https://images.unsplash.com/photo-1555215695-3004980ad54e?w=800',
    images: [
      'https://images.unsplash.com/photo-1555215695-3004980ad54e?w=800',
      'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=800',
    ],
    pickupZone: 'Cotonou centre — livraison possible',
    includedZones: ['Cotonou', 'Abomey-Calavi'],
    features: ['Sièges sport', 'Système BMW iDrive', 'Caméra 360°', 'Affichage tête haute', 'Climatisation'],
    rentalPolicy: 'Permis valide exigé. Carburant à la charge du locataire.',
    cancellationPolicy: 'Annulation gratuite 48h avant. Caution restituée sous 3 jours ouvrés.',
    whatsappPhone: WHATSAPP,
    status: 'active',
    created_at: '2024-01-03T00:00:00Z',
  },
  {
    id: 'car-4',
    slug: 'range-rover-sport-2023',
    title: 'Range Rover Sport 2023',
    brand: 'Land Rover',
    model: 'Range Rover Sport',
    year: 2023,
    category: 'SUV',
    city: 'Porto-Novo',
    pricePerDay: 110000,
    depositAmount: 250000,
    chauffeurAvailable: true,
    chauffeurPricePerDay: 30000,
    transmission: 'automatic',
    fuelType: 'diesel',
    seats: 5,
    description:
      'Le Range Rover Sport représente le summum du luxe tout-terrain. Idéal pour explorer le Bénin avec style et confort.',
    mainImageUrl: 'https://images.unsplash.com/photo-1617469767053-d3b523a0b982?w=800',
    images: [
      'https://images.unsplash.com/photo-1617469767053-d3b523a0b982?w=800',
      'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?w=800',
    ],
    pickupZone: 'Porto-Novo et Cotonou',
    includedZones: ['Porto-Novo', 'Cotonou', 'Bohicon'],
    features: ['Toit panoramique', 'Suspension pneumatique', 'Système Meridian audio', 'Cuir Nappa', 'GPS intégré'],
    rentalPolicy: 'Permis international recommandé. Carburant diesel non inclus. Kilométrage plafonné à 300 km/jour.',
    cancellationPolicy: 'Annulation gratuite 72h avant prise en charge.',
    whatsappPhone: WHATSAPP,
    status: 'active',
    created_at: '2024-01-04T00:00:00Z',
  },
  {
    id: 'car-5',
    slug: 'toyota-prado-2021',
    title: 'Toyota Prado 2021',
    brand: 'Toyota',
    model: 'Prado',
    year: 2021,
    category: 'SUV',
    city: 'Cotonou',
    pricePerDay: 65000,
    depositAmount: 130000,
    chauffeurAvailable: true,
    chauffeurPricePerDay: 18000,
    transmission: 'automatic',
    fuelType: 'diesel',
    seats: 7,
    description:
      'Le Toyota Prado est un SUV fiable et confortable, parfait pour les familles et les groupes. Excellent rapport qualité-prix pour vos déplacements au Bénin.',
    mainImageUrl: 'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=800',
    images: [
      'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=800',
      'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?w=800',
    ],
    pickupZone: 'Cotonou — livraison possible dans la ville',
    includedZones: ['Cotonou', 'Abomey-Calavi', 'Ouidah'],
    features: ['7 places', 'Climatisation arrière', 'Troisième rangée rabattable', 'GPS', 'Grand coffre'],
    rentalPolicy: 'Permis valide requis. Carburant non inclus. Idéal familles et groupes.',
    cancellationPolicy: 'Annulation gratuite 48h avant. Caution restituée après inspection.',
    whatsappPhone: WHATSAPP,
    status: 'active',
    created_at: '2024-01-05T00:00:00Z',
  },
  {
    id: 'car-6',
    slug: 'honda-civic-2022',
    title: 'Honda Civic 2022',
    brand: 'Honda',
    model: 'Civic',
    year: 2022,
    category: 'Berline',
    city: 'Cotonou',
    pricePerDay: 35000,
    depositAmount: 70000,
    chauffeurAvailable: false,
    chauffeurPricePerDay: 0,
    transmission: 'manual',
    fuelType: 'petrol',
    seats: 5,
    description:
      'La Honda Civic est une berline économique et fiable, idéale pour les déplacements quotidiens à Cotonou. Faible consommation et grande maniabilité en ville.',
    mainImageUrl: 'https://images.unsplash.com/photo-1494976388531-d1058494cdd8?w=800',
    images: [
      'https://images.unsplash.com/photo-1494976388531-d1058494cdd8?w=800',
    ],
    pickupZone: 'Cotonou centre',
    includedZones: ['Cotonou'],
    features: ['Climatisation', 'Bluetooth', 'USB', 'Économique en carburant'],
    rentalPolicy: 'Permis valide requis. Carburant à la charge du locataire.',
    cancellationPolicy: 'Annulation gratuite 24h avant. Caution restituée après vérification.',
    whatsappPhone: WHATSAPP,
    status: 'active',
    created_at: '2024-01-06T00:00:00Z',
  },
  {
    id: 'car-7',
    slug: 'toyota-camry-2023',
    title: 'Toyota Camry 2023',
    brand: 'Toyota',
    model: 'Camry',
    year: 2023,
    category: 'Berline',
    city: 'Parakou',
    pricePerDay: 45000,
    depositAmount: 90000,
    chauffeurAvailable: true,
    chauffeurPricePerDay: 15000,
    transmission: 'automatic',
    fuelType: 'hybrid',
    seats: 5,
    description:
      'La Toyota Camry hybride offre une expérience de conduite douce et économe en carburant. Parfaite pour les longs trajets au Bénin.',
    mainImageUrl: 'https://images.unsplash.com/photo-1542362567-b07e54358753?w=800',
    images: [
      'https://images.unsplash.com/photo-1542362567-b07e54358753?w=800',
    ],
    pickupZone: 'Parakou centre',
    includedZones: ['Parakou', 'Tchaourou', 'N\'Dali'],
    features: ['Hybride — économique', 'Climatisation', 'Caméra de recul', 'Bluetooth', 'Grand coffre'],
    rentalPolicy: 'Permis valide requis. Carburant hybride non inclus.',
    cancellationPolicy: 'Annulation gratuite 48h avant prise en charge.',
    whatsappPhone: WHATSAPP,
    status: 'active',
    created_at: '2024-01-07T00:00:00Z',
  },
  {
    id: 'car-8',
    slug: 'hyundai-tucson-2022',
    title: 'Hyundai Tucson 2022',
    brand: 'Hyundai',
    model: 'Tucson',
    year: 2022,
    category: 'SUV',
    city: 'Cotonou',
    pricePerDay: 50000,
    depositAmount: 100000,
    chauffeurAvailable: false,
    chauffeurPricePerDay: 0,
    transmission: 'automatic',
    fuelType: 'petrol',
    seats: 5,
    description:
      'Le Hyundai Tucson est un SUV compact moderne et polyvalent. Design élégant, technologie avancée et confort pour vos aventures au Bénin.',
    mainImageUrl: 'https://images.unsplash.com/photo-1468818438311-4bab781ab9b8?w=800',
    images: [
      'https://images.unsplash.com/photo-1468818438311-4bab781ab9b8?w=800',
    ],
    pickupZone: 'Cotonou',
    includedZones: ['Cotonou', 'Abomey-Calavi'],
    features: ['Toit panoramique', 'Caméra 360°', 'Climatisation automatique', 'Bluetooth', 'USB-C'],
    rentalPolicy: 'Permis valide requis. Carburant non inclus.',
    cancellationPolicy: 'Annulation gratuite 48h avant prise en charge.',
    whatsappPhone: WHATSAPP,
    status: 'active',
    created_at: '2024-01-08T00:00:00Z',
  },
];

export const mockUsers = [
  {
    id: 'user-1',
    full_name: 'Kofi Mensah',
    email: 'kofi.mensah@example.com',
    phone: '+229 97 12 34 56',
    role: 'customer' as const,
    created_at: '2024-01-15T00:00:00Z',
  },
  {
    id: 'user-2',
    full_name: 'Aisha Diallo',
    email: 'aisha.diallo@example.com',
    phone: '+229 96 78 90 12',
    role: 'customer' as const,
    created_at: '2024-01-20T00:00:00Z',
  },
  {
    id: 'admin-1',
    full_name: 'Admin WeCar',
    email: 'admin@wecar.bj',
    phone: '+229 95 00 00 01',
    role: 'admin' as const,
    created_at: '2024-01-01T00:00:00Z',
  },
];
